<?php
/**
 * QueryTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  InfluxDB2Generated
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Influx API Service
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 4.0.1-SNAPSHOT
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the model.
 */

namespace InfluxDB2Generated;

use PHPUnit\Framework\TestCase;

/**
 * QueryTest Class Doc Comment
 *
 * @category    Class
 * @description query influx with specified return formatting. The spec and query fields are mutually exclusive.
 * @package     InfluxDB2Generated
 * @author      OpenAPI Generator team
 * @link        https://openapi-generator.tech
 */
class QueryTest extends TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "Query"
     */
    public function testQuery()
    {
    }

    /**
     * Test attribute "query"
     */
    public function testPropertyQuery()
    {
    }

    /**
     * Test attribute "spec"
     */
    public function testPropertySpec()
    {
    }

    /**
     * Test attribute "type"
     */
    public function testPropertyType()
    {
    }

    /**
     * Test attribute "db"
     */
    public function testPropertyDb()
    {
    }

    /**
     * Test attribute "rp"
     */
    public function testPropertyRp()
    {
    }

    /**
     * Test attribute "cluster"
     */
    public function testPropertyCluster()
    {
    }

    /**
     * Test attribute "dialect"
     */
    public function testPropertyDialect()
    {
    }
}
