<?php
/**
 * V1ViewPropertiesTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  InfluxDB2Generated
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Influx API Service
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: 0.1.0
 * 
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 4.0.0-SNAPSHOT
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the model.
 */

namespace InfluxDB2Generated;

use PHPUnit\Framework\TestCase;

/**
 * V1ViewPropertiesTest Class Doc Comment
 *
 * @category    Class
 * @description V1ViewProperties
 * @package     InfluxDB2Generated
 * @author      OpenAPI Generator team
 * @link        https://openapi-generator.tech
 */
class V1ViewPropertiesTest extends TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "V1ViewProperties"
     */
    public function testV1ViewProperties()
    {
    }

    /**
     * Test attribute "type"
     */
    public function testPropertyType()
    {
    }

    /**
     * Test attribute "queries"
     */
    public function testPropertyQueries()
    {
    }

    /**
     * Test attribute "axes"
     */
    public function testPropertyAxes()
    {
    }

    /**
     * Test attribute "graph_type"
     */
    public function testPropertyGraphType()
    {
    }

    /**
     * Test attribute "colors"
     */
    public function testPropertyColors()
    {
    }

    /**
     * Test attribute "legend"
     */
    public function testPropertyLegend()
    {
    }

    /**
     * Test attribute "table_options"
     */
    public function testPropertyTableOptions()
    {
    }

    /**
     * Test attribute "field_options"
     */
    public function testPropertyFieldOptions()
    {
    }

    /**
     * Test attribute "time_format"
     */
    public function testPropertyTimeFormat()
    {
    }

    /**
     * Test attribute "decimal_points"
     */
    public function testPropertyDecimalPoints()
    {
    }
}
