<?php
/**
 * XYGeom
 *
 * PHP version 5
 *
 * @category Class
 * @package  InfluxDB2
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * InfluxDB OSS API Service
 *
 * The InfluxDB v2 API provides a programmatic interface for all interactions with InfluxDB. Access the InfluxDB API using the `/api/v2/` endpoint.
 *
 * OpenAPI spec version: 2.0.0
 * 
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 3.3.4
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace InfluxDB2\Model;
use \InfluxDB2\ObjectSerializer;

/**
 * XYGeom Class Doc Comment
 *
 * @category Class
 * @package  InfluxDB2
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class XYGeom
{
    /**
     * Possible values of this enum
     */
    const LINE = 'line';
    const STEP = 'step';
    const STACKED = 'stacked';
    const BAR = 'bar';
    const MONOTONE_X = 'monotoneX';
    const STEP_BEFORE = 'stepBefore';
    const STEP_AFTER = 'stepAfter';
    
    /**
     * Gets allowable values of the enum
     * @return string[]
     */
    public static function getAllowableEnumValues()
    {
        return [
            self::LINE,
            self::STEP,
            self::STACKED,
            self::BAR,
            self::MONOTONE_X,
            self::STEP_BEFORE,
            self::STEP_AFTER,
        ];
    }
}


